### ISSUE TITLE
Feature request: Usage of System Categories

### ISSUE THREAD

**Issue by mathiaslim** [pegasuswerbeagentur/google_for_jobs#11]
Since TYPO3 6.2 it is possible to categorize pages, content elements and
files (default setting) by using the internal generic categorization system.

Activating categorization by providing category flexform element for job
entries would be great as sys_category could be used to f.e. colorize
job-items according their category in List- and Detail-View.

(sys_category UID - only first category if more than one category is
selected per job entry - could be set f.e. as class on wrapping div)

**Comment by Micha-sus** [comment]
Hi @mathiaslim ,

sys_category support was implemented in the latest releases:
- TYPO3 10: https://github.com/pegasuswerbeagentur/google_for_jobs/tree/2.1.0
- TYPO3 9: https://github.com/pegasuswerbeagentur/google_for_jobs/tree/1.5.0
