### ISSUE TITLE
Missing Logo in Frontend JSON

### ISSUE THREAD

**Issue by firmenpunkt** [pegasuswerbeagentur/google_for_jobs#13]
On selecting the hiring Organization Logo the entry will be made on the backend, but the JSON script created on the front end does not contain it.

**Comment by Micha-sus** [comment]
Hi @firmenpunkt ,

the missing organization logo url was added to the JSON output in the latest releases:

- TYPO3 10: https://github.com/pegasuswerbeagentur/google_for_jobs/tree/2.1.0
- TYPO3 9: https://github.com/pegasuswerbeagentur/google_for_jobs/tree/1.5.0
