### ISSUE TITLE
Show Job title in BE list view

### ISSUE THREAD

**Issue by RicoMahr** [pegasuswerbeagentur/google_for_jobs#14]
![belistview](https://user-images.githubusercontent.com/30402023/110597739-3da63880-8181-11eb-9dd1-cef04977621d.png)

**Comment by Micha-sus** [comment]
Hi @RicoMahr 
this was resolved with 1275b5edec86dc3aded55159d4cca4cfc1498d23 for TYPO3 10 and 6cb5733f4e6d91a9febe09472f91c42d8cf5e7d1 for TYPO3 9. Please update your extension to the latest version.
