### ISSUE TITLE
Jobs with multiple locations, joblist titles

### ISSUE THREAD

**Issue by firmenpunkt** [pegasuswerbeagentur/google_for_jobs#7]
Hi, a very useful and cool extension, thx!
I would have two feature requests/issues, if I may. At the moment it is only possible to post a job at one location. But if a company has multiple subsidiaries, and the same job is offered at multiple locations, one has to copy the job for each branch. It would be nice, if the editor could add several locations to the same job, and the json script would contain all jobLocation entries.

A second issue is the Joblist in the container. At the moment it is very difficult to find the job to be edited, as the joblist contains the datum of each job. It would be much more useful, if the editor could see the tite of each job instead. 
![joblist](https://user-images.githubusercontent.com/15831707/70073345-faadfa80-15f8-11ea-9740-06fa5f395112.JPG)
Thanks, Ákos

**Comment by Micha-sus** [comment]
Hi Ákos, thank you for your feedback!
I just checked the google for jobs documentation and saw that google allows for multiple job locations. If implemented, google shows the most suitable job location in the search result, based on the location of the user.
Concerning your second issue, it would indeed be helpful to see the job title as the title of the backend record.

I will try to implement your feature requests and prepare a new release over the weekend!

**Comment by firmenpunkt** [comment]
Hi Micha,

Thx a lot :) . the second issue is quite simple, I have found the location: row 5 in tx_googleforjobs_domain_model_job.php 
Instead of  'label' => 'date_posted',  one should write  'label' => 'title',
