### ISSUE TITLE
understanding installation documentation

### ISSUE THREAD

**Issue by deanguis** [pegasuswerbeagentur/google_for_jobs#8]
Hello together,
maybe you could help me with this, but I'm not really sure what you mean with the following items in your installation steps:
- "Create a plugin on a page"
I guess you mean a plugin content element and select Google for Jobs? But on which page should I create the plugin? On every page where a job posting is located? 
- "pid = <page id containing news records>"
??? Which news records do you mean here? Or which page id do I need here?
- "pageId = <your detail page id>"
Same here. Which page id do I need?

I'd really love to use your plugin, but as I'm at the beginning with typo3 I'd really appreciate your help with this!

**Comment by muellerp** [comment]
Hello deanguis,
sorry for the late reply.

You have to put a plugin content element on the page where you want to see the list view and one where you want to see the detail view.
Furthermore you need a folder where you can store the job records.
The "pid" is the id of your job record folder.
The "pageId" is the id of the detail view page.

I'm hoping I could help you.
Best regards
Pascal
